permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: write
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'chromium version'
        required: false
        default: ''
      type:
        description: 'runner?'
        required: false
        default: 'ubuntu-latest'
  schedule:
   - cron: '0 1 * * *'

env:
  CHR_VERSION: ${{ github.event.inputs.version }}
  NEW_VERSION: ${{ null }}

name: Builds and pushes tagged image to DockerHub
jobs:
  generate_build_deps:
    name: Generate Build Deps
    runs-on: ${{ fromJSON( format('["ubuntu-latest", "{0}"]', github.event.inputs.type) )[github.event.inputs.type != ''] }}
    steps:
      - name: Reclaiming disk space on / by removing dotnet/android/ghc
        #if: ${{ github.event.inputs.type == '' }}
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo apt-get remove google-cloud-cli azure-cli google-chrome-stable \
                       firefox mysql-server-core-8.0 mono-devel podman \
                       powershell
          sudo apt-get autoremove

      - name: Enable proxy on container
        shell: bash
        if: ${{ github.event.inputs.type != 'ubuntu-latest' }}
        run: |
          if ! [[ -z "${HTTP_PROXY}" ]]; then
            PROXY_ADDR=http://$(hostname -I | cut -d' ' -f1 | xargs):8118
            echo "PROXY_ADDR=$PROXY_ADDR" >> $GITHUB_ENV
            sudo iptables -D INPUT -p tcp -s localhost --dport 8118 -j ACCEPT
            sudo iptables -D INPUT -p tcp --dport 8118 -j DROP
          fi

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: cromite
          fetch-depth: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check versions
        shell: bash
        run: |
          if [ -z $CHR_VERSION ]; then
            CHR_VERSION=$(curl -s https://omahaproxy.appspot.com/all.json | jq '.[] | select(.os | contains("win64")) | .versions[] | select(.channel | contains("stable")) | .current_version' | xargs)
            echo "CHR_VERSION=$CHR_VERSION" >> $GITHUB_ENV
          fi

      - name: Building build-deps container ${{ env.VERSION }}
        shell: bash
        run: |
          IS_PRESENT=$(docker inspect --type=image uazo/build-deps:$CHR_VERSION > /dev/null ; echo $?)
          if [ $IS_PRESENT -ne "0" ]; then
            IS_PRESENT=$(docker manifest inspect uazo/build-deps:$CHR_VERSION > /dev/null ; echo $?)
            if [ $IS_PRESENT -ne "0" ]; then
              DOCKER_BUILDKIT=1 docker build -t uazo/build-deps:$CHR_VERSION \
                --progress plain \
                --build-arg VERSION=$CHR_VERSION \
                --build-arg HTTP_PROXY="$PROXY_ADDR" \
                --no-cache \
                cromite/tools/images/build-deps/.

              docker push uazo/build-deps:$CHR_VERSION
              echo "NEW_VERSION=$CHR_VERSION" >> $GITHUB_ENV
            fi
          fi

      - name: Building chromium container ${{ env.VERSION }}
        shell: bash
        run: |
          IS_PRESENT=$(docker inspect --type=image uazo/chromium:$CHR_VERSION > /dev/null ; echo $?)
          if [ $IS_PRESENT -ne "0" ]; then
            IS_PRESENT=$(docker manifest inspect uazo/chromium:$CHR_VERSION > /dev/null ; echo $?)
            if [ $IS_PRESENT -ne "0" ]; then
              DOCKER_BUILDKIT=1 docker build -t uazo/chromium:$CHR_VERSION \
                --progress plain \
                --build-arg VERSION=$CHR_VERSION \
                --build-arg HTTP_PROXY="$PROXY_ADDR" \
                cromite/tools/images/chr-source/.

              docker push uazo/chromium:$CHR_VERSION
              echo "NEW_VERSION=$CHR_VERSION" >> $GITHUB_ENV
            fi
          fi

      - name: Create issue ${{ env.VERSION }}
        if: "${{ env.NEW_VERSION != '' }}"
        shell: bash
        run: |
          GH=../../gh_2.18.1_linux_amd64/bin/gh
          wget https://github.com/cli/cli/releases/download/v2.18.1/gh_2.18.1_linux_amd64.tar.gz
          tar xfz gh_2.18.1_linux_amd64.tar.gz

          cd cromite/tools
          echo ${{ secrets.GITHUB_TOKEN }} | $GH auth login --with-token
          $GH issue create -t "$CHR_VERSION: new chromium version" -b ""
